# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8d4f43e1a68d8027d48172c0b15ea0a45cf1cecbe89ed92117557b922dffc2dfc9ba3e60feb5f4a1de817ce24fe3be717f9cb9830b32dbf600b54f144be05bd

test:
  secret_key_base: 09a1bf5b573bdf7e97c7e77620d3ac0cadf23d5ea75cd644453b808243ca830aa55d968a911477bc2dbfd418a00f76abb60de68f0098b6cd2984232b3e0d1d09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
